import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'My awesome site!',
  description: 'Generated by create next app + Sanity',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
